#!/bin/sh
timedatectl set-ntp true
echo -e "n\np\n\n\n\nw" | fdisk /dev/sda
mkfs.ext4 /dev/sda1
mount /dev/sda1 /mnt
sed -e 's,arch.mirror.constant.com,mirror.isoc.org.il/pub,g' /etc/pacman.d/mirrorlist
pacstrap /mnt base sudo grub linux-headers xorg lxde virtualbox-guest-utils
genfstab -U /mnt >> /mnt/etc/fstab  
arch-chroot /mnt grub-install --target=i386-pc /deb/sda 
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg 
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Asia/Jerusalem /etc/localtime 
arch-chroot /mnt hwclock --systohc 
arch-chroot /mnt sed -e 's,#en_US.UTF-8,en_US.UTF-8,g' /etc/locale.gen/mirrorlist 
arch-chroot /mnt locale-gen
arch-chroot /mnt useradd -m -G wheel,video,audio vm
arch-chroot /mnt echo 'a' | tee /etc/hostname
arch-chroot /mnt systemctl enable dhcpcd
arch-chroot /mnt systemctl enable lxdm
echo '%wheel ALL=(ALL) ALL' | sudo EDITOR='tee -a' visudo
reboot